name: 'GitHub Actions Morning Greetings'

on:
  push:
  schedule:
    - cron: '0 4,13,21 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: 'Checkout Codes'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
      - name: 'Install pip packages' 
        run: |
            pip install --upgrade pip
            pip install Beautifulsoup4
            pip install -U requests
            pip install -U simplejson
            pip install -U lxml
            pip install -U fake_useragent
      - name: 'Get Date'
        run: echo "APP_VERSION=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: 'Morning Greetings' 
        run: bash greetings.sh ${{ secrets.USER }} ${{ secrets.PARTY }} ${{ secrets.CORP_ID }} ${{ secrets.CORP_SECRET }}
      - name: 'Clean file' 
        run: rm -f morning_greetings.html
